Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/02/2026
Var
// Seção de Declarações das variáveis 
   primeiro_numero: inteiro
   segundo_numero: inteiro
   soma: inteiro
   subtracao: inteiro
   multiplicacao: inteiro
   divisao: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   // ENTRADA DE DADOS
   escreva("Digite o primeiro número: ")
   leia(primeiro_numero)
   
   escreva("Digite o segundo número: ")
   leia(segundo_numero)

   // PROCESSAMENTO
   soma <- primeiro_numero + segundo_numero
   subtracao <- primeiro_numero - segundo_numero
   multiplicacao <- primeiro_numero * segundo_numero
   divisao <- primeiro_numero / segundo_numero
   
   // SAÍDA
   escreval
   escreval("Soma: ", soma)
   escreval("Subtração: ", subtracao)
   escreval("Multiplicação: ", multiplicacao)
   escreval("Divisão: ", divisao)
   

Fimalgoritmo