Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/02/2026
Var
// Seção de Declarações das variáveis 
  // nome_da_variável: tipo
  nome: caractere
  idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   // ENTRADA DE DADOS
   escreva("Digite seu nome: ")
   leia(nome)
   
   escreva("Digite sua idade: ")
   leia(idade)
   
   // SAÍDA DE DADOS
   escreval
   escreval
   escreval
   escreval("Nome: ", nome)
   escreval("Idade: ", idade, " anos")

Fimalgoritmo